version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn youbetter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nosql:
    build:
      context: ./couchdb
      dockerfile: Dockerfile.prod
    volumes:
      - couchdb_data:/opt/couchdb/data/
    expose:
      - 5984
    env_file:
      - ./.env.prod.nosql

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 9001:80
    depends_on:
      - web
      - nosql

volumes:
  postgres_data:
  couchdb_data:
  static_volume:
  media_volume:
