version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - nosql

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=youbetter
      - POSTGRES_PASSWORD=youbetter
      - POSTGRES_DB=youbetter_dev

  nosql:
    build: ./couchdb
    volumes:
      - couchdb_data:/opt/couchdb/data/
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=youbetter
      - COUCHDB_PASSWORD=youbetter
      - COUCH_PERUSER=true

volumes:
  postgres_data:
  couchdb_data:
