# Generated by Django 3.0.7 on 2020-06-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nosql_token',
            field=models.BinaryField(default=b'gAAAAABe95P1XV_hVllvhdwogdlbjVx2MGsbF3S8THWiC2tAKyQNnlmkVqI2OJZ2cx_s8UJLLLfVe4iEaprK44iYA29kNZJwGmf6oRWr74sJ0HoF206WqbM=', max_length=150),
            preserve_default=False,
        ),
    ]
